# Generated by Django 4.2.4 on 2023-08-08 07:35

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Task',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='Days', chained_model_field='Days', default=1, on_delete=django.db.models.deletion.CASCADE, to='studentapp.task'),
            preserve_default=False,
        ),
    ]
