# Generated by Django 4.2.4 on 2023-08-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_student_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Image',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
